fix compatibility for newer versions  & add servo support
jadonk/node-roboticscape pull request #5
Opened 2018-07-18 14:51 UTC by vaishnav98

replaced some deprecated functions
modified binding.gyp to choose sources based on rc_version
added servo support , used @chnewso 's fork for reference
tested on:
 BeagleBone Blue BeagleBoard.org Debian Image 2018-03-05
Linux beaglebone 4.9.105-ti-r113
rc_version : 0.4.4

2018-07-18 14:53 UTC, vaishnav98 commented
https://github.com/jadonk/node-roboticscape/issues/4
https://github.com/jadonk/node-roboticscape/issues/3

2018-07-25 17:19 UTC, jadonk requested changes
Until I can see what changed in the source, I don't want to approve the merge yet. Go ahead and remove support for the old API.

2018-07-25 17:19 UTC, jadonk commented on binding.gyp
> +	    "variables": {
Indentation looks different.

2018-07-25 17:19 UTC, jadonk commented on binding.gyp
> +            "conditions": [
Please use 0.4.4 and obsolete use for the older library. In fact, James has recently made a 1.0.0 release: https://github.com/StrawsonDesign/librobotcontrol/releases/tag/V1.0.0

It should be 0.4.4 compatible, I hope.

2018-07-25 17:19 UTC, jadonk commented on rc-node-bindings041.cc
> +#include <nan.h>
Please don't create a new file. We can obsolete support for the old API. I'd like to see what changed in this file.

2018-07-25 20:41 UTC, closed without merging

2018-07-25 20:54 UTC, vaishnav98 commented
submiited https://github.com/jadonk/node-roboticscape/pull/6 after making the recommended changes